global:
  namespace: sneakerhead-dev
  environment: dev
  storageClassName: nfs-client
  labels:
    partOf: sneakerhead
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: yaswanthreddy1602/sneakerhead-frontend
    tag: dev-89825ce
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    cpuUtilization: 60
    memoryUtilization: 70
  config:
    VITE_API_URL: /api/v1
  probes:
    liveness:
      path: /
      port: 80
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    readiness:
      path: /
      port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
user-service:
  enabled: true
  replicaCount: 2
  image:
    repository: yaswanthreddy1602/sneakerhead-user-service
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 8001
  service:
    type: ClusterIP
    port: 8001
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  config:
    JWT_ALGORITHM: HS256
    ACCESS_TOKEN_EXPIRE_MINUTES: '30'
    REFRESH_TOKEN_EXPIRE_DAYS: '7'
    LOG_LEVEL: DEBUG
  sealedSecrets:
    DATABASE_URL: AgAFmZe+onnEu4bO43oHX3mCIeecZBPuJG23A9g9ncF/qefQy/dVc9/TwW3NjLfKMqRMQ4mSABnJ0jRGhAru/QSUPEnOaiOBoJrF0HVF3NSKewe12JRsaSH3w3avOlxI7Npx+CeH8YgFwIUbQ86u6jKfgIuQOTIUaQUvMdUDs6Dwxq3H/Hjo1wRb2bqdwTUngVa1cxvApAElj3v0fig4kLvmsr0NCKKV0kLul4JLrcSjfH8Q4by+Lz+2ZavKFoGOgSEwSoIe1GDAqni0Ykxf3KSejedStLmPgImQ72y9zxo2wWCy8LoGXCMMQN+LLJQV7ZJu29hM4p4TA77+meamFdOBMy+zoLOKLX3wWoupbF4YMUT6AVU2/9gnBirmeXI2DogGx+Qn6xQwfWoUnctnEduRnlXby7xMFkMjmGEfrzTJjp+AZGYZ4/RZnOXTlq/fS+0g6F66AyhsgHCO3gib1Dx8VLw9g7Cg4MG1Wyx+IifPG/r2robz9PsaV6lCCgjg1OskE6IocHmwVbAV5kWI4XugVBbzSlYvlL2jvO0FvNdGKc945P1UjMng7AUVcyN6Da555iUBTJZSACSfIBfG41sQY9CcQ9gVI1MnKWyB0azzuGOnJ1wFmWTYjkyHyjF7KERxOO98cNpy7jE0R5Cd2+gyzWU/5f3QGFYifn3sQiKFyTgTj9jR7cfOr1zbCGmq/TkxD70IuKAd6vBxy37JFtvPEc2rg+Qn7Sn0GuhURYJbHxTtpc10fm6jy+xClytmC0WTkB1rx2Fi/KHq0PBUXAxkfwqMdTc=
    JWT_SECRET: AgAhajWEhJvYQJEypUEfp1HXAAX/v9N52uCYDPy4EwYPo0vXS5MaADa8UvHPLgPX6fXgAKFX3vYoMZY4n6vXRGhI0nW/0aiThDXrO9eyzDdHVGnIkopiBGj0rvLYaW1VAN1ucvhrDtAta10BpRTEqnp6byRImoJkDjQsa5x4SV1Tw/EdcULBc6beP2pPU3xhMs32VZPaVtnL2l3r0jW2ketR9Js4+Lv+HlUv+7vIZHFer3G5AhBuln4v8R4VLD7gAGDniEZloycFhnaZGqmUDtasY9C55CWndhfzGZKyCjGsJsafcZ96RuFczJA8TniOcj7A2JPrv94Sn0a6vn/4zHYOG6P5kHt+qpfQPR0srK1jTdLnsqczbRCXEVNWQDyd56VXHojzP8m9+pfbFt1Xkgo9e0NL8W+gnpOOAf6Qba+6edM9PMa0kJ8dkkfyJCblxFnjMwzERQXLvDdN720rW5rMXVPokkXNXsTu0974ykXAj+Xpga4ZI70Z9Ti1BywrLkbr+BtbSdTh4NmaEdLtSFNJKJIwJ6mh9E6/KQIhAEECQtnj8avZdF9Em4wy+pQ4mBJlwuU6mXtHbTfh/hXy71DWHpxtZK73/DK/2/PT2Km6jerriM0iRcitF1Q35WYBdY0hdcugmPXQ6dlwrXbnOFCkw54n4Wt0U3tm8QbVwPK4gvRyQFLX+khqQwTxBZoAw7Fd0LTTqe2aVkjWTRoI6zbV0kIVks5j2MFTjMLkIc0nKrXbDBx4qwms95il7wBz
  probes:
    liveness:
      path: /health
      port: 8001
      initialDelaySeconds: 40
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readiness:
      path: /health
      port: 8001
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
product-service:
  enabled: true
  replicaCount: 2
  image:
    repository: yaswanthreddy1602/sneakerhead-product-service
    tag: dev-601ec4d
    pullPolicy: IfNotPresent
  containerPort: 8002
  service:
    type: ClusterIP
    port: 8002
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  config:
    JWT_ALGORITHM: HS256
    LOG_LEVEL: DEBUG
  sealedSecrets:
    DATABASE_URL: AgBtzxXWPXRPjAsSNnUWVpQw8pohNnx8po88gVYabCWFlZSqrvLBPKedrLI8tiKTad5YZjv0NPq1jNgX6vgb0PCNwNhsToJSAZrio9Sc6Sf7C6Mjnfh5vhtEoxSewiCnHy0pSpcsyDDx4fjgzxETe+f7d2cag/NL2n9c79UYYr3dSbGYX4OQdto7Zn87XjGUx7ul86SLevwA9l8c8evJ95pdsI7ct5TBDIGNz2Cjk1T8kWCLDvC/EMKe+n3zzdEurnfttfX2NuX/3Ua2+TWmCNYYqd0ICtMxXBMctnY/KQ4o7zTFNin04XRBKeTCivLNziBY0PwTZExmtVB3xJvsSPLT8HD0B+eKbQ5BL4P3ppdF+RolCv11TuDMrXWhx375A8l3q3NkQKpirdbfEfFbrzSMLFpNg2AOGmT+qQX93pd7AeNTATBTpEPzGAaDcvnynFrTnLJB45Qv0KwE5NzlObV0Is4TeW7m1l1dhWUcPJBrR5jUMRpnb7AXGy2JCjf1xAo1anbuOtGvhdptbPq1OIJsDSgXYvPIA55eIdWTHMaqMtxvVPn5/4XS6Ts8q+b1iOEFW6VhEFm1H0/5RyNDTj6GH01nYR6JLBGWsNO1XdyKkr0m8zJbVdal58HlT7QGDqWx0kiVM/n1JF4zPg9JXGwQ4sEX9Gr4SaDxhjmireLz6zRbBiUqEOALH/2IrkT/Le62mQipEYAqG0jHSlcUs0mJAXQvYn1iElUm3IKBcX3OpF2bmYrHQa8baLGZICY/JsfHxelxh+mlZsymzHiIJ82dV6628/L8kE7ivkE=
    JWT_SECRET: AgB/ZaSyeOAvL+COEPZ8LsPNCDd9yIxufrHSzpJlVse7AjqtbEI43z1lQPpfitloF1e/y2r7NrFLux0I0VZpLZWpeygAxCqzEjsnfRQbIyHVygOTQPR/iar3fGZSPWcGGblH+LT/On0SLK2BQZqLcZ2jWCVxoB7AvUfjt1mqSI9fHTFmE4NL35YcSy9DYGxYfPjRHcZUEzlCH1TXsjbIaeiDGQt/ksIX97YVxAkXqHmgg9v96eUP9nNxdjSXBUhQv914SC8UPq75xzYomLUiVkvN/hcWxwQyCaDRKkeEzS2r1n9Q8Tn+ONvvv2b/U0UTgq8DJQ62aCeeWDB8q7Id8kRx0EgM3skpRuhpty2jCRUosqHLaX1DvO2Z0NqMc935cvZpY3cmYizcIu35hYuOj+qMEuYrw12wPbqlop/s1cYwimnClwfDXiJ1ORBeyMO3jF9DJI5ocQs7KlDVB1wV2r7c/68aMM164+q556GhPiNndUDOIQ4ip+90u+m5pHma2ilTmHwhaQ0eDQy0cKWUE7j8XrLsF6wU9qIlanRnpbUHSVl7CwVVWJiY9zvSo+V/qVWa/eGa2cOQLoMdz8zihpnYHDmLXcDpW0TxiNl1RkymiR81KoH8JpcNFFx2ISEaha51A9rKl93D7B63MhewohNgeDo6o9nffkbpweX3BsUVRq7YpnD1/ys2N8Ag9XLz1O/FiJmju1PtYD29yXTPK0+4ma0CJ8rDfvZI06h/clpMVON7d7R0MQmmR8k5ekNy
  probes:
    liveness:
      path: /health
      port: 8002
      initialDelaySeconds: 40
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readiness:
      path: /health
      port: 8002
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
order-service:
  enabled: true
  replicaCount: 2
  image:
    repository: yaswanthreddy1602/sneakerhead-order-service
    tag: dev-3fd6e00
    pullPolicy: IfNotPresent
  containerPort: 8003
  service:
    type: ClusterIP
    port: 8003
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  config:
    JWT_ALGORITHM: HS256
    LOG_LEVEL: DEBUG
    USER_SERVICE_URL: http://user-service:8001
    PRODUCT_SERVICE_URL: http://product-service:8002
  sealedSecrets:
    DATABASE_URL: AgBWPeF6PvZXSmHHSK7psg1YzhA/idarkrAZyadYZMX5oWHQPSl0WpuJvRCVNWGRec22oiTtCMKuKV9UiJTXFbaGfE576dMznhc/7AgPksYM21H0rbTrAyP/x07o0mPcn6v2NyrxBl7UpZs5ysTGEI9ao2udoUiCjngypoxR/035tJiE6WS/IRndT7wphXWZKWif1Xrd5j07FEbmmXfE7o3oWiJjfmHLE7j1SZVzFuvtRMi66prHhH6UqCTX6AyB+AiJnNKBAP7O7lMRrXPwTk1U+5yMNaNDknPzMhXOMSHiTbaz9KbVr2Wi1gLPbvk7AQ5pVDepduBbzUtn/mXqqi/KifzVtuhm7/Gjv5ANBVuks5w7qgQJRnsmQ4wiuG0YpSXmrVijld3P9TT+/onM2MCIizk/tEQUEo/thWNp7OUaI5JqYRXyLQWzDtets962NaIOjKBacil09PjqjxpldBpiqlV+/ky/R/b/YQ6HMeLEfhpjqNEEY060DF6pBh7Dz1mN4SF6c5TEHLoGyihzfKBsL+XBdpfKv8iy1P5Wzhx4TlwGBjfo43ccOqWRN4ZVLq10o7CLxYZrsvomcHLzgGYzcWo7e+GVtqL/mK3pZROhaiebTzDYHGBlel61PgEixpb0XRsikEmuO0uqr7vfq31CEX657hk1qv87fldHcdRCbMK5Ci7TfttRPZT0LF0FQghVJFk2gk8auBKhuCQAqWCg+zsvRAkj/vZlgyKHV3ddPhhg8Uvne/gj5524aqewuLFxA4x4Vj4iyrbA/DQYDa75kko0NysCcg==
    JWT_SECRET: AgCGMdvpvcpD8s9hi9HOp6Xmog5EgPou9nmnWe30Btv6cqxYw2iAE5F7eYrnaMZYmwuI5yZOlHT9er3LEuJanL90W3zUFi2sQJbKgAymKsPZW26zqVmLsLr8buOH75xXN5cjHk+655QKQI5X+dfkvLOX6BTbFPGaQZKC1Yau784e/AQYyEN9xNtQxzzw102dEwZY2FdhNNUCJP2Zklfqo2klB5vsDM1rFkGw3aNYq5/mTWFwLhbP591DOqSAEnJ1crmbhp+djSdjMJIeQe2IgaQcbSd71vHYXFefzoJ7OU6Ml6kqAtrD78H8IoNI4c1HEuA0CAymVVW2RcccIBevmGiYqLcptrf1j1VoovNDCoQJM6jY7XUR8kieET3DP+4wqYfWgd8kr6HGrKT6Ifi28z7llRSkoFZOCA7Wc3EVdMFw0UTSUBclxHQdqHoSYwRY/WlvO2u0oajjR42rG7bZ1H7pvd3RyWbt0XubTNv61NzUGjNPtHJiAjnSOzml+aLU+P3uEuTrMmzezyijL1T6F1Z8Y2fYcxu+WySIKHVZXCJQKRKWtfoQOuIb4B3DT3cDHyOIIAl2Kb6sGeP+qd3RW2P0OhwFi/lHSIqnn+yAy9+r9AoDpL87O4cTmAAqQRcfixiOl7OR1uArHen7EVFBQiAoiZ2H8rtuByqlWqhiSiTBDemsObC2mR3yeaUBK9GhL2IhvKcb71CAZAFAiL5FZBgFUfAWon4ay9uSr9pCmIfolsTzZkt2NL15GWJpTMur
  probes:
    liveness:
      path: /health
      port: 8003
      initialDelaySeconds: 40
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readiness:
      path: /health
      port: 8003
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
user-postgres:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage:
    size: 2Gi
  config:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: userdb
  sealedSecrets:
    POSTGRES_USER: AgCIZrMrDvTuPs5q46mzG7ZJvL+Xk2NJ6w/aqSHVwhP78FX7n70/Um2MaJ7TalD90JZd0+bv2OTnsZeHOKo+aABPDR0U9oovxWGhNnhKOsOkh57KAojtHH93xgwksA1Xlirj4zSE3O9OReNZhrXEMkX/Y4U2eUxbUOv2sLMY5cXAyhkJe+ueIla4TXQK4J20+I0Wj7dAP/3DMggO3vUmm7mNDvl1C79BMI9MqSe2I0H/bbo9ivgWMRnzjGUnp4g3KfI0Hf7JiMroH2xBXkm1uBJb93YejGPK+ygaBV5YlW1uP2hmSIV6XDeiYLTGlQ64pA/mTchVFPV0ykTHZjM3vpn8T+Qm4+CVXKryAIb+7M3OblDGsC4knECkVK4NLD5NKLFw21JQhU4BB62fez5AXMDjuPNNDYMmvVb4TCuuTyVIJpOW9xTCz4vE1qFCVp7B6Sz3fOprGlQbRu854ClrifDsEAYSJBfyI4uAM7JFpCwVDxo8QX2gQuAt+FjKA3XbpNP+sl1ua72+gDasWmyqPgM8TJltTdPiG5gxN3NzpvXEzc+E1pWub3j23PlVW/eCOOaDhluxpzzg88qqJPoIpnlFld+rmKrGd8uSTSh1fTOFOaeUu1lrfU7piisJM82qBwANcg7ovMhIfqX/TkkVS8iWwQT6F0aUYJUCNPa/ug98Mw6CTQpWs/bfzUwpE+dsKHn7MxU5DjhL
    POSTGRES_PASSWORD: AgBtp9hfRrrhGhQ2ADmt6qu1khKIu+iyjRJSSTNrrSe+2H95HV3aD4QFPCBUhFw0PTFQnBLfbYVle/bzdH/e3yy4vG6uPL8LrTh0DQHd+Zj7E7eE19ieIvPa1Jm+gDR/XU1vOkz0okJCNww9/bP97mU7EfsxBXzQ7iqaxVbfqBNpRE0ED7g8b8aPTPRiwtEdVgdpny94iL342JL1s2+bVFP4hEagyRRs0M29uQDFAz9kGquabC92j5tJN2MBDupR8jaZg65ZdYjrBaHcSkoHj3CV0Ptg5lqmUZmxRM+pMKT1kRc3hrnIfPGBxR3HvoP40aa0oCk28igmau19hNfoO3IWntQGhM8yriXCAQz07ABClLVFpxTIRKAxNXCas5pjWdVRzfc26AxSlVPtcI8tOACuPOhMd3XXbMM7QLt5ZOUSy3yhC13rHg3XTM4d+m2P8fZf+TfsNW8v1RvSM4CKwyVy+6xiwoOQ9GGqQmERtI36Ah/Hfq8hVukWC2KqcABzeIiQaLNyKAdUxWreJwtFknjFwpN89NB6Dfma7sIqfkjpe9G1JSvaKm5Y/bbftVo7XBOJwzxm9MUjez2iXcqtdq0cTZQHGypiWBxkyymHFA1lsZM5TfBzx0BERuXS/kFr+rYQ4zkp7G63Dus/5hS4WcaL/NEtxMEyAK0BjFrGZtDWLFzSnZaTZHv47JqG6vlSkDWFO+ykbw1JtHaWrjMldg==
  probes:
    dbUser: sneaker
    dbName: userdb
product-postgres:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage:
    size: 2Gi
  config:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: productdb
  sealedSecrets:
    POSTGRES_USER: AgAd19/CsFNfxDutjAooxiow8Tq1HIKme6AY19ycNmOw5AXyinftb0i8nxt5vfEQ1yVUleDQvjtuzpCpZijwTXlxroCWIuEGS2DgFScIChNrxfltT6N6DNNqJCu5L+bu3EOXrgiFx0CY86/LD4YvOdPUoA0XtCMMnLesvG1otQNCq91Ek1dxwmvWjsYxSt4uhYDGP5tcPGsDoXCMovYa3a15Q/XG/swZJ90EZR1M0gp5+BBRbSJejFFE1outpfPwdNnSUwhHG4C9OmK6T6t8bjGXWfBRxIQxyLdy1ZNWw5cvMy0PSIbAmLv2s8NnXcct2xjtVlP2C6nc5drvKZk78zLzIUsseOb1pZfaVDnK4m7K/ywPu9te5gbGSdxpIkxb5ulGINF+qxNWM6uWxQusi5Y7lzCahUm4Ej4bFQE/XBxUXAvLWSQ1bre3CCYNPEXcEA1aqSr1CB7Lz7bc36oJ9L4R+rN2rVa+CIfWJIQ7xT23y0cQfZVDGWJZ1eJjjKzj0xQ/B0ZYRncIKopSA4xAlg7l+dmQGo5XL93Fu5deJPNVYS01+3PkZG/SWbszS1gNtdYcd8dd+WlcZzAw+ANoPSsIXFBhspuaxYqKeaWPnFdJTGEZgBApOPPOwdKtiXrSoENyJr1amv5yZPNRM12wQDSuqYVyCVXwMfZEv3aO2HpDHoScq02zZtjLB5BaN204F5+xvldNjAKN
    POSTGRES_PASSWORD: AgAqdMkqGJ0wcbLx2t1v3vTs5wubwNckw6LlBAO+HS+hufTeYG2ofh0ziXugM5UthqIPrqVpGfU1E3f+PYhO5lf6B/MwdEdaxWcoM9vhJPpTAeeQx2F64P52Ly87pQODHQE7h2zyNTDK0DAMCpO2C4xCnan8ed9gQWYHVLfAmlmtuqIsC5E0BkySDUiLR+pdBw7Y7yPYHM7n14+3zO5VNOmu8DnX5BDbOim9DPeK8s48J28R/RJNlX9NBNdvc5VMCb3gitZgrzHMO0UOrCVP4wbuCFAtvh2HIRtX1TJ/PD2QKWB8g6/j6xwvhp7UNJE8dRU4D+9PvOi24vnYyBY7/uNxNzy7sGsx/h/ejPXw3zN4zcMZIMhwebunBVN10AFhu/xaNgAyRbvFCjrTwxZMAhTrWQgozI2cprEcWQhIO+SwChBkZZSbo6X3tM2IOi5KUugmhRA9EbO5hcVwvA4lZVNOEh/kqSVFqDr/OnxwwXj09842OndVmB7ns01ujYsWFQNeMxFBb+lRHN1KmXeu+vVIJSWGuP13cOq/a/pZJ1sgWaDeWJAwcLsF3fOGAGZf8YmMZ+nClrjuV80GiCGyWK5Av/YwGKP05QG4y7Hht+40t2+uqfv63JfupjDxafizvz3bAQuMUHsvt/FIS1/Tz8uLh5KoWMZAZZsuLCnKfj5rs8ZrFCFjbKyUSs63N4izw4HZ07PWAB0qQm07X8Z6dw==
  probes:
    dbUser: sneaker
    dbName: productdb
order-postgres:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage:
    size: 2Gi
  config:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: orderdb
  sealedSecrets:
    POSTGRES_USER: AgCCOOcw4GGNyVlR+3jAQNN35Ghj5itZREbhkKYbGgSS1c2D1TpIy/p6qjW6gEJt8/6KzhEZExGGNzOS2YiwaTNofiq8kgETiP17hW3gcJ6JEbGEkiTSkjLCp+fwKkCZvX6rqS1JutIAuqOyVzeeKoOw8gk/jAgmHKRSFkx5GscWKTSiHUXxhZH0HY7SeRFNEvFdBv73VvT44LeaCn61FjWIN/rxJOF2t7coofMXvC25c1/eCFzXPUDn9bOLR1JI9TyWbcLcagA9ExMWuu3Nd/JE9cQaAr0a9Wk71o1YpFLpnQO93ZlGVLbGeyi42G+USnZnjpV5R0C9s/wE18Y/1dehpRTgYBSG0o4GBWS6RLgPFebhnmYu5cdmKnAOEUzkSa5GKWVWtf/En0lL5IsmKhbv1Dh2EdYNGtSYzPnQ/bFBPteKabq54mzhlZgQeNeIHvBUz16mGUVILGy5EXZLCytlox+6Mlu/JmIecpTSHoLIuMrons0IvQJXFr4+Vj9gHXSOBu35ZeyEqt6CVn9QM/P3LzLvG+MG8ZsQzAGk0/G+d5FbhXl96B4UifYKnmI0A/MVAH+edLl3jsCRVds/urS8uooftJaUA+jyKMVa6WWOwX3fnCtN4w0Ag2ne+xBQ8p5D1hFbXv84W4tkzuq2oNIaYwsSDGNKJ/tLyfrTodrccboN61p8Dl183uwfu5irLs1k+FWuFrQ5
    POSTGRES_PASSWORD: AgB6+ZPbn+V4pGPdBs4cj9UwGcMC7eW+Qgq5O19/JPkPgpCfGlPhRXn3i+tWBTb+mxsnK9rUKLQZx3Cj6ezRniYyGCUSPl5ZpsA84mcmJ0VUcr3KxK6pLtE6PyMyIWnlEMFDQgd9g+FfO+8+EAQJ/LCVVc03Am301f2VYPYc+ku2YVdofCX9b3WA27gAkYZlgXCMcUXQaa7gmystW8hZHr7myuslvvAwkAXdSjv++yukgKsVXG/l0j07cd6Wbq6MIG2s6QgtPCE6Gw1koXXsX25qB3pncOSgv1GdfysN3Fk3L2CCIxMNfPg5oWiqfj+0YvWVQ59HEaBAyiw6a7jZnS9RxVm47C5VBIV6hHVFA5Z/aFfpYAfmhMygbn1YCdffxE55TD3k8b22LJn4xZ6HAXsypOomG+rtWve8mMc18urBTbHl/lddDwwYQgDK52ywYfRWR7a5xL4gfbqqT32eJ9X6J1OdmPuUkZVS7zxRz4d5hEhvMRwwOb+jWWteP/3rCADb7YSn7JXMwErqKQ+N8zQ28WaYBMXyanhNR+BtDlR700QVmPghtGEj3iHfDR4T5Fb+OHRj7AjrTE1F7GdpXkX2KizyLV8xL1imZ9/A5YqOp14JU4vyveTha+zb/wgpoHKQ9FDW54Qg0wAs+ZIANq4WRhxV6xpZPZXKLFEG549aFxqzUoPOSyoc2Lz/FR0V4rDbqUzdWy/BmWSPki+q2w==
  probes:
    dbUser: sneaker
    dbName: orderdb
gateway:
  enabled: true
  gatewayClassName: kgateway
  listenerPort: 80
  listenerProtocol: HTTP
  routes:
  - name: user-service-route
    paths:
    - /api/v1/auth
    - /api/v1/users
    backendService: user-service
    backendPort: 8001
  - name: product-service-route
    paths:
    - /api/v1/products
    backendService: product-service
    backendPort: 8002
  - name: order-service-route
    paths:
    - /api/v1/cart
    - /api/v1/orders
    backendService: order-service
    backendPort: 8003
  - name: frontend-route
    paths:
    - /
    backendService: frontend-service
    backendPort: 80
network-policies:
  enabled: true
  gatewayPodSelector: app.kubernetes.io/name
  gatewayPodSelectorValue: sneakerhead-gateway
  kgatewayNamespace: kgateway-system
  xdsPort: 9977
rbac:
  enabled: true
  roleName: sneakerhead-dev-role
  roleBindingName: sneakerhead-dev-rolebinding
  groupName: sneakerhead-dev-team
  rules:
  - apiGroups:
    - ''
    resources:
    - pods
    - services
    - configmaps
    - secrets
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - apps
    resources:
    - deployments
    - statefulsets
    - replicasets
    - daemonsets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - autoscaling
    resources:
    - horizontalpodautoscalers
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
    - ingresses
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - gateway.networking.k8s.io
    resources:
    - gateways
    - httproutes
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
