global:
  namespace: sneakerhead-prod
  environment: prod
  storageClassName: nfs-client
  labels:
    partOf: sneakerhead
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: yaswanthreddy1602/sneakerhead-frontend
    tag: v0.1.2
    pullPolicy: Always
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    cpuUtilization: 60
    memoryUtilization: 70
  config:
    VITE_API_URL: /api/v1
  probes:
    liveness:
      path: /
      port: 80
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    readiness:
      path: /
      port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
user-service:
  enabled: true
  replicaCount: 2
  image:
    repository: yaswanthreddy1602/sneakerhead-user-service
    tag: v0.1.6
    pullPolicy: Always
  containerPort: 8001
  service:
    type: ClusterIP
    port: 8001
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  config:
    JWT_ALGORITHM: HS256
    ACCESS_TOKEN_EXPIRE_MINUTES: '30'
    REFRESH_TOKEN_EXPIRE_DAYS: '7'
    LOG_LEVEL: INFO
  sealedSecrets:
    DATABASE_URL: AgCgUVoV4PC1SyYPY4f5FTkMHoY9hLYpCb+umzDqCGjbUlEDRF7ieUIjZFJjEQuOu11czkea0BpiYmy5AvZj4e5RsZFnXUHvHqnhPaQ9h5STPEs59vqBgt87gw+O0UPiusZaxVwu5oVKSpeHEHn3pP0VYBaC91mar+hBoCiS2ekxaf5FqRfzhry0nYi0TbpmnTs39rd6aLSne3NHSxvi6rbJ8uqDLrgwHwhuj1YpE9qybEeQQn/yJIBd34ZrysTxJ51UrLstHKaUsiNzPw6gtMto+cr5z0COBp+d63MAzVHWpUAXoaToQ/Ezod1LncUmZ+QoyNiB0Dp0VPEi+lXtedKL7taaLLuwcYWp+/0NNUxvvlvEHtaeW+uLGBnGLGjpQUKycdFQP02j6YJoHaB0fEt0vkAH4XEYjgQsk4dgZwWt3LKF3rUL92rh72vqTdszawXejLfwfhTzax6wr2pa+GA9PWh5dx8t9yxaNU/XjFrgN1aUYycWe23L2kq329vvloCa7rj4lvRLiLByPiFHoHwA1S4N/aHmiP1cnVaW99VycIu4WfK1jIcPNKZetsnJOKpdkLeNyXCKl778JoGMimPo0aUiPmH94Pyt09Q8qaqGH+DVT2/diyFLo4RV7wkw7S0g2holbWHnnzsTt2t0mHrP07JSRfmKMgH4/apLK/GqTHUUKcbgOyRP1gnKD8TV7+WS5hrFxNMuv1m8TRcxkFZodPWt6rmV9baRjSc2C97belqLAFQlKvUws/XCaga1ZoBDplZhCEe8YLBCWLwPHDrRu4aX9Zc=
    JWT_SECRET: AgCKaLcdPlZvG/gwjaUEYM6B8WG4g97qGuhxWG4wToBmGIi+h9B/+5ETKxFfjsR/iwSFuZZk+q0s4oH8a51yfs8tneKCcBPxqKo27IufhXz7ymA8PssUQVBzApt5jIOyQVfHst8YXdNvvbs2InzW9/5zGy3k5TLnA01vEDUApGd4wW3OOv+vyY8qzvGIXRuE8gkOzedWuBfMdbe783ZHIEPCh+pSLTIUms1zcLk2lQ0HKpLVqN17U4p4tmumviQXgK91N6wDRryz2jo50p1jUwaDwvP++7/NXDD9LKFGp7+hC15zAniVA3ezKlK9n1ZVKXhdJB85c+wVtOn/DTuFHHJ1SlD6zHyeJmofhJnENWe463s0/YpX+pVo3VgE5ZQ9cPaJV7CCTJPNllFJKNAIAUxN1unZoBIUBhwZUjirKTiil25AdMH8UavygUXNNEARsCGmWDVCbam+gSPova7gSjcleEUr2uoTq6CY6sgMFjwP5dfOzHKQeHqc/jcSFYiT7Cz5aaDnsmPzg8RXhj/Au2YE0WOa/JqTxGqL5LdlwKbMqUzBM86FJLG22yuzwwcFGGIEgaJcT737k40nPxKsqeoF1HGiDoHnjxLiZ3DQVvZuUjD+IlI576XLYLKES/oWcbpHoQxbRNZnD8CLuCHRYgN/cvZ9yIKsmMlte7fOAs6DL4t+yCN6RtE3gtUEQKnk/cB8iOdAoXt+uSruRMqJblIx2NHo6ROrbnItWlSSO2YOKQPMy3gevWJWJfn8vanJ
  probes:
    liveness:
      path: /health
      port: 8001
      initialDelaySeconds: 40
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readiness:
      path: /health
      port: 8001
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
product-service:
  enabled: true
  replicaCount: 2
  image:
    repository: yaswanthreddy1602/sneakerhead-product-service
    tag: v0.0.4
    pullPolicy: Always
  containerPort: 8002
  service:
    type: ClusterIP
    port: 8002
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  config:
    JWT_ALGORITHM: HS256
    LOG_LEVEL: INFO
  sealedSecrets:
    DATABASE_URL: AgBlj/JzCkvGwSpEvHnBvcQb0lipCs0RfvlwYVvT3cvY19c0mtNQFfwt0JmsZf6jYykWbbNSQzUO7rtCJM5iMYgAK+/RnqUlkNgRGEj38SOF4YTpqJpC4YDAy319wPTWyL4aM5X3aIC8cUZ3jYeTV6TSOcjXmtKiy1nSmj6OGip68NDuzk59s6U+v2BnBL3g3Nnk8iivAbfiw0gTtM9UfExtkv4XBva1Z32I11Xj9uiqvX8g/JJUysDpbGWjQs9uE0YRPP8UCNm9XvqVRsIFzGlj9w83hfy+53/TZB514Nf07X0LmMDk89U0olF9jkWC3LgxTgnXNud3t544ariGjNGhNiFXM5UIQU6fO5Yt3s3ncng51zciS1rwBS4mw+Dakrx+WChKBMcwazQhKjb7BXHodp4aEshyS0IL0gZckp54b3fuTL1tDf173oAHD077C0Nk9QphFK1HIpJ2VvTokU2DpjIXrdz9DiC+QdfVwXZjugemaUpclQf/Ed531IRP+QxRs9S/3bAQfQCm42lk/PlZ3Wo/3RqOpie3wxqvJP9E/l+/4y5IDinSbDvxIC2lkD0bwQUppKdEQ+IuTXpwFEzObsiNTDot07NoInBSWlpY2RQaQnSrpiH8RqmiP1WUprouIfpkqPLQAGYnn2svUnXH0lp3t0jJX55IDLnWwb1341ztKuVEj2tK5ycy0CNVKoov0q8pIsIOG54P9x1gcE1zRcL1ftfumHPyPRMgWnsZophgs3KkjRyLWgm6sPdXWp2Nb87yKPfN1zJG1cMWqJOhtEEsuoYmroOFDrE=
    JWT_SECRET: AgCOBzvXfrcFHsmWV/lwIXxn33eAweil/rquaO3Mc4Deph7/HN33UkhTYbe3lQiRrmGd54umsE42oOBj2RcyQWRiv0u1p5TbMpLCtAS9j16XVMM2WfOGqTahB8RHtgy8xy1FN3poN646ThL0ODxlZZ51k0fb27hQhjQbR+ZWSzmYcWC3pExAinE9LnntNbGjgayLRgWi22xYKl7ZhwYJIn2WnuuZiPkAnlG4iD2IwIpBF+OrzOwTmWQx1Z8NZvN928uUMwzagjM7kit5IIUdxXZ5B3DKEkfR44DWrMjuLPCZjfgkpkj1MHUx+pkafypXEQUhKmuUfw27q9izyhL2C1BSiD15AK7NDK/ncL6e8eLlOMYzsRjOmGGYjtL+xhJaH9th1/zkGmfWQOfcX8Chfr36uU7x8V04NcRLj6Tp+3ybW5AFblOkc78P+iVKzEte4WIzRFRkzwwiOJgTiywm56yWQ5SoGpsKRa2f7Q0mAcSjexni3ZFZIkYLE35J3/aJBhvZabu0eppccEcK9kuaIIdOv/Dhvlr9PJSCQ6w15IQV1FYenrF4Z+8rUtNGKCRNBeS7vA6/g7UyBZYwqn7ZRs9yprfTemalbM2faIHdTQk7vzoGZSZBqNHUxVV874DJinjMsPlfwkjERn4RuX82Q3KyPmJguZWG8FTYpOSFI44hyIBTyTdhzH/liJMapU6GBunVZDq0Nj2XmItaROxIG/Cfz3khdRTLU6gThNYXFPoSEKPn1BGUaNUCDizT7P7c
  probes:
    liveness:
      path: /health
      port: 8002
      initialDelaySeconds: 40
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readiness:
      path: /health
      port: 8002
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
order-service:
  enabled: true
  replicaCount: 2
  image:
    repository: yaswanthreddy1602/sneakerhead-order-service
    tag: v0.0.6
    pullPolicy: Always
  containerPort: 8003
  service:
    type: ClusterIP
    port: 8003
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  config:
    JWT_ALGORITHM: HS256
    LOG_LEVEL: INFO
    USER_SERVICE_URL: http://user-service:8001
    PRODUCT_SERVICE_URL: http://product-service:8002
  sealedSecrets:
    DATABASE_URL: AgC+tQqpJPsUigoG3KSTzbg0bjkdfHEIcvF795aNUoayJKjH6Kz6pgjmTmEkivkVJjbJG+m0IL3MfzpivHgDFZCk8PLuvM15LhfH/Dy0Txp/fkbJw/sSzSkc5InwfGJjN7s5c1gwzKRqkMwS/fjaSU0DjQ0NsFf9Y348fA0Y99Fiab+JrR9HhtbwMzaUCBYc4vJxixB6qqIkJi0mwKAoKIsn3THr1FIAxrcTAGqRvurmgB/mqfAm1UEmFmwY/9xxdAdBCdaQ9d5ATSA9V+XSTQiOZtoIbiiAffQVzTkkTd4Cps4oiGU99YjOpFDELTinrCx+kuYb/yuz7tqjb4S6rW/8ddOE2YlTqzvC4yFYsDObxk/xdI/hcU5rtAmHJJJyCAiIXcZAglcp8+6c5huDAWiJPBg/Bp6+RgKVFh6+agSMvC9AyqOfTOc24MaVMWzb0lGtET33yon+H+TPzYp8uP+0S9f/seeVUe+GFAwKSK6StfIZPLoAih2FMUuRUrFZviN+/Mb/D1mDHrq2enPakoQZR5gR9tXJoF5uEsppxmXCpzyBj0t/o1U6zA4AyToUIofwzM6t2zeVQIw4tVcArdwWWdqg0iIDbLU4SKRHaHG47aBx6tld2xhwrF5HOIvnYlsEQRmV/KSdFumcOcJ/3Wh7E137yjcKA7KwkF6i+9eA3Vgh1bzAKPiZ4zS4q/+EsG4EWRtreClhBkjONmiMECOy0XuHFHjbnb9CfgvIbI8DLmEDP3szYlmm3HSIy2UHiAW2XIJWxj7yhgT2TVpq0t74T+UQHr7HpA==
    JWT_SECRET: AgARaXdnDB79DTcWQhaKOBJhlgZ1u6lhciY7amp3iiz0tiR67b+6a+NL8exJ19n7Eyn0j5EaBG6s5tNgqf5xjSUg0hfGlwVWxQE5EZ9v1QXi4Hge5q3/5T9Mjx15obA594HBfJa6+poqeRK0/eNgbi6Vmcx+26h9ukEQH5FhyVSzZofIBhuqcTZakc1yFZKVqiL2au7GrYaviqsnRLQOSI9jyQYkGJ1jy0IpMJ91bjUUcMdnIqgKNqqJXE5MtE77MpDysnfxuYO58KdCy876g+8wBwvqtyCQXWSlVAj+dXgMVWBmxjeDUF1NbjW/JOwq9AbkagmmRIwpb7Yu0HARwqKImmGm/5MqQFLZn36CzrDD4qx7wRbryq+XMOjPMgt5L6jclHhRVv51rsyrIMxsG89dvv6s9iBpm74kIferDXAgfp7OQSB5sLNYL6LkIw1HUODCbJLpGt7r65/UdiOh3at2lbbR5jMN5HuMABNS4YtqmfpqA0b02Dhj1fzZbt+V5sOsisUosxv44kEDKax0qD2ZEUQsMcN4tRYB9hLealGO4ZPWnKLtmyfsjWcUiKN0gpvV5XfbcrtQsnK7Ykrl8S8yj3vU46w8XZVb/0hX3Z8giyH0HB41NDBn1evFiZvmI+BLoVlWmDFZeFg/txlxYzPAXZ4TJJFHvppMunIIhDdPgWy1CdQPW7hYNIGBDgd6s5a8qfggCDfw91z58ArV2cvs71Oelh3d9oTCh8RXhz9i/OhuWsixbFUeFTZhxYGp
  probes:
    liveness:
      path: /health
      port: 8003
      initialDelaySeconds: 40
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readiness:
      path: /health
      port: 8003
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
user-postgres:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: '1'
      memory: 1Gi
  storage:
    size: 4Gi
  config:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: userdb
  sealedSecrets:
    POSTGRES_USER: AgCbZUAVs5oGb/swBWNoccVInP05fRG1gc4Y9j2evYdf//nK3GExeBLnsdlTBjONMezLgytacLVwTn4FWfj4mvy4sxw1XtyaHC2UT87xUZI8puzH9Wa42Y1t07/p4Q4sWTpyKDEbVOzeelH+yjMuuvERrpFfo0bbNOkpmwzNRJRe2Ogv9YC32hpNU5PQjbMm5LA+XtXna8SI3J6sjfiJIZFO/B81PIlIVVbJCDMEGe/6zaKdWJ+ciwwPF45QZhZ0ctTp/So3eSlsnty8dSpPPVlHpy9psnWPRYLj0JXNoNmHEYWBmMIfGMLyYXyfWplDf1VrYxjDoh0PuYs5YcHdOQ01s0UJMYiwJcIojLOhlTEhtWF1yF8km+xVqkL2XQQ9U4Z0FlJ7YCSddcAgqC3nYXdRTaarFJ6Y2+0QWLk5foHq2Gv1sQSp6V22wPTIbG9d6MlpdabpLPSfaTe7GRXuz6Lwx39txGNqwwfWcUqZK4LfsxqaifiZR+1Rda/WKAY2WQ7umxIOw8TUaomIOc4tp4pDH5jafgBolRPPwLXYMgBv+SLWmCyAXX6fFbV+PzBrBcURddyg2gTMDcS62Owf7Q+j0crOXEHdmouVgR2MFEb3no6ncmFeFIMpOqWPEhUOD+uur+8I39CmcEus1mRVJQPGhVA4rBG1cfkAIeproEc0QueraYsMydhOAVcBv+SpJNunPBFAtL4k
    POSTGRES_PASSWORD: AgC3Z6NJXRQuT421qjN3ts24W0HoXFxRmwCBSoe+03vnv9tdn6lh91q2V6RSg362df93qKdD86nWCujWJI1QkpNz24+LCALrCExtfCC0S805xGhFxp6kPoDEgNXIjx8y5FX21T7hcakPleY1Z1SMZX+Wzqlli36wouIdAk8rkWfNJIdhApancSX/GAYyxRnsL6tRX6HHvdTwHFXY9ZYOOY1PaUMZrzNACyWns+GHUTKWqrB8OaTcSpUbWJ/ybAao4o5ya5Xnia+BlvYifHfgiGu0y4jYl/h8/jzTNSYkcEdSIx5bohPGWko5HDbdWe7I9evlfIGuLJpbllLjz3Xrr87U8Ed3FBcVUIkiq+zBGGvG6Rw73U/p1yuRpBRTiRHkLcXYmzgtYFjiXLeYyHeC9wNYcqkgI3RxPEIhoI0ECRs9MDcUUJ3hp6dWkDTmSvgbYm5LxghTeY8JvbeLCvOgs8DIILQJlsz55pOhU+YywweKngKIGDoEqsnETGprcPzCucz+hE/EpQ5Ik0wP/p+ifU7ovgM018y1OfnMqMOlewNv41iv2jNg9wUWpOv4TUkDn/dF92L3LHSCBSYjvq1LNCk+Iq7hkhkRuIJdbboQ1O25SnbK9b5TwCTVRoz5K740JkDTUG0uXC0dxhf9seMx1j6LfQ4ieBtAZYJl5nCULmpL/5ruefVonDw48DPu62AJ2zUVhK+DaDlzMrF/4AzNMA==
  probes:
    dbUser: sneaker
    dbName: userdb
product-postgres:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: '1'
      memory: 1Gi
  storage:
    size: 4Gi
  config:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: productdb
  sealedSecrets:
    POSTGRES_USER: AgBeJt+C9psnXayN4cD6a9kKVw2CdBsNBw6+8wSJkjndeENs+OMxz6ZK8dSFWPiqoY8kP6NqEApoBRMc2OcLCSDMtSqEnx2c3phqoi1JHb1CBvd4UL6U5uIs82/olZNsLCN5Lgx2NnKZkqyMyWYAD0eLPLdc869oa1Ny7F+vzZmNM0VFgQcAN/l4vQ2P//twqe9DeWV420AH6o8o1coELGsjLf6C4FvN19I/PQPBNPN05+4ck2uQrTWoUnNGr5XDDnKkLVLGKS9SlAm1V0YxEmLNLYlWxm0WBj19kwiwGVaDAiLeFB2Q3r1vJ/qsfsfVmPofyNx+RXNLnrYCrvKW+hVMrUBCJTcbpL3ctwWgMUaPUqYw5Mh3JVuSXVyhrtcCIICOcdeJc4u9fShojQFEB2Oo/WcGhLYQ17wpJr8OdLbc05xAUdYkpGD5trsHkmgfS7tbwtyWwOkggdpQnp4qz/EV7o0drHjEnB1iKrSI+Ia9TarTLqf0vnOrQQ9QdsMnYRbjPDRbRt7O9zCzjkNsoLBFlnhs4smRnRW5mcVPfIlRtCg2TPTOJwTh2tzgqWauQGMZZRvfLMQbRNqiv17nwKJH7W+cVxGYSxPIkefsiIWMLiWw07lqoTOMc6pvOEw1FvX7RY3gaZhd7Jc43U4CsLeyo9PUjBoCoxj1wc8FX+K61HmGuIFmd2RCmom0FHO/HvtEcDhaxis1
    POSTGRES_PASSWORD: AgAGfFatCTnqPlTupj7lwtUc98JUSkGcZ76+wgZ5Aj2SdDpIzPtXv+ld8CAPljnL4Y/c531nZ3/A/Nk4GMzFXgb+D7Oip9LBiYxCyIB9UWMo0E8YFrbJtX7iQb4ZjCrcuJvTJfFYIhUnJxNv8PzHh/eE1SlkIBcmT9I9/1jXA+S7VrBpSfi9jQel37f1ttgWC18giMHHPjfRzS9EttUaGZ4w1eCVroYfItvG7L7nUNRXI+L8akFdxCGDQAxHSm+6hhBQZXcBpBz/C92gL5+OIveIV8qz0nTHI+LFZgfLS7MhCx2mJbhI4XdqHfQ18YZ5kC+oVKsAxDoVQWrSjfSEKUzLuZyG1uVPfJt0OvO2DvhLmJ66/CPGxrbcDO/q3S7WnAoON3UuopXXwkxiIqRakS80d3mIfERNXT6kBt2iOTzLrXuPjlcqslwG/cCzUkG4938EFZgFV+IHTSspmraZ/91pWPuUoN6FUt6cKqvIIqaPbEQjKKlG+qKa/uvzD48xzyJLdqnbFN3P4PuMcD5V+sDYsmmLg91GcrsCQrUKBsw5FcV1eC4WdepGr3VkXsHwp3YtiTQZWxGVdu7dkrHX3KpTVLty5diTvsWRRVbSG8EXUHNDCL4fZb2kUc045kUf34tqD1vb/hm2FMuU2ZizwZ+u8yP5b8fBo7dJtzpVFrS72/nYWL/ZQ5mmhIVmKwyl959tp7xU+CX7W0RyieKH0A==
  probes:
    dbUser: sneaker
    dbName: productdb
order-postgres:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: '1'
      memory: 1Gi
  storage:
    size: 4Gi
  config:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: orderdb
  sealedSecrets:
    POSTGRES_USER: AgCcjrKRhDLzrnOXIsvmNczyvuhm+OMWs9+qEZkjgWM91QSPzgE4VulCDE95nlKEYt7Jd6Y7JgQE9fVoUIiq8vdmTcLijWTVPnS/hhX0RrDCO3V4sy5Zsy1Dh2icxYTxeLs3suDZtICr/bD60rjBtCmLOni2UAsupNhEnQ/W9oBOb4B6Vt68kRvrWLLFsroQFmcbxiXfqow0pM0IMKkmoktEkL4s0rxpY7NoO/RmecfVBFFs4LH7LWeHWm36N2qJadtHll7IUh8LcjHwedCHwIlzFURV2NDFQQbYeMP2hFa8iJ2+34mr4wh0ihUTT/+SFjKjhxGuzuGxRToeFObO6QsPBjkByacsRLRTBp+CtxXMQwpwL+kpXlurD8bIFZMUYoj/BbTFURCnitRsfXdVmcFbj4K1KprgLeErQuAsQsAqNiIcIx53j6u0y+kBnHm4HfySGpM01J5ysr34vLbcWoKHaQtOJskf/2yiBC28Niv5CANADHYjOMJz7A/rKvWdg++rG+kSaitl5Z5c7CNjU8QryJ81jF2HLsdtgwKwsWHTjYvWI3aB43cHChP7BC/AacvMS8jZm8ESU0LLrCvczJujByQIRrOiL80JwV8jLbgsQHpvsFp6nBG89vBsFxyk8RJuUXOghdNc9al35q5WFYaSCTtk8Yy/F0ltNyiGgr4GmkpWtMRIYdgZ0aKX2KjsweVuQGVogxdy
    POSTGRES_PASSWORD: AgCve0LNcaQv8H6lLBfPGFx5LctKh63SiBpOi0v9FJFlJpuckBDaoqkchV8rHA3cnQVcKNj/nEEm9cJHhLt0Fhr0yNoNcfIW/KQXeCRiRkWNuGTpoS8l3byN9TMeiSCrw+V7LtWBlLF+yIFnFN8Jsd+l1SmKed+GUe5eekzdlTJWMrXzNKr3Yg5/wdX6DWnqgxxw9apiX5Uffhg+koRq7rOklY2Va86c4/oPcwtvzGPp4uPd2Mbps6xNbN7ljiIObqTgjrrlB3KvEWy7dR9mrNcVrrFaY/0J+PLHx1X9KuWQEGAFy/u6nC4ih3IaOs2Sqd8tCauAZgao8gdJ40/C09zjyfaw390T6MJ3CHTKj8j8mcR1XaN7MxvGh65IBJ6SYBVecByS/ZlxGLl47axUyye+tTRncbkFjzbbHjG2eXuv9gogWu1Zkfq5JyO7F1X9aF5+TBebX0IUvGjI/hSgdZH18HkJYpr+P70wQnS7LBdA0bukcVAuBb4dvJLx8O8vV0CNh/6pVv0FJuDw6FHD9pkFsy0CiN9oX4LoOw2qfbPfuQa514ZV83LVvHSa/aTCRPsJ0UJsqXoMjLWZFAmsKUbc8INzxOXWVLN2ggANYigudcQ0Mh8zQ1C81zJLvJBnFZmWLLnT6fdre74a5U0f49VH1qmegHKx6pOI467klYEKa0m0HqlhnaetJji7jkTm7Stz7UNHpNXpA/7EFb2PCA==
  probes:
    dbUser: sneaker
    dbName: orderdb
gateway:
  enabled: true
  gatewayClassName: kgateway
  listenerPort: 80
  listenerProtocol: HTTP
  routes:
    - name: user-service-route
      paths:
        - /api/v1/auth
        - /api/v1/users
      backendService: user-service
      backendPort: 8001
    - name: product-service-route
      paths:
        - /api/v1/products
      backendService: product-service
      backendPort: 8002
    - name: order-service-route
      paths:
        - /api/v1/cart
        - /api/v1/orders
      backendService: order-service
      backendPort: 8003
    - name: frontend-route
      paths:
        - /
      backendService: frontend-service
      backendPort: 80
network-policies:
  enabled: true
  gatewayPodSelector: app.kubernetes.io/name
  gatewayPodSelectorValue: sneakerhead-gateway
  kgatewayNamespace: kgateway-system
  xdsPort: 9977
rbac:
  enabled: true
  roleName: sneakerhead-prod-role
  roleBindingName: sneakerhead-prod-rolebinding
  groupName: oidc:sneakerhead-prod-team
  # ClusterRole: grants namespace list permission for Headlamp namespace dropdown
  clusterRole:
    enabled: true
    name: sneakerhead-prod-ns-viewer
    bindingName: sneakerhead-prod-ns-viewer-binding
  rules:
    - apiGroups:
        - ''
      resources:
        - pods
        - services
        - configmaps
        - secrets
        - persistentvolumeclaims
        - endpoints
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - apps
      resources:
        - deployments
        - statefulsets
        - replicasets
        - daemonsets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - batch
      resources:
        - jobs
        - cronjobs
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - autoscaling
      resources:
        - horizontalpodautoscalers
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - networking.k8s.io
      resources:
        - networkpolicies
        - ingresses
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - gateway.networking.k8s.io
      resources:
        - gateways
        - httproutes
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - apps
      resources:
        - deployments
        - statefulsets
      verbs:
        - update
        - patch
