apiVersion: v1
kind: ConfigMap
metadata:
  name: user-postgres-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: user-postgres
    tier: data
    app.kubernetes.io/part-of: {{ .Values.global.labels.partOf }}
    environment: {{ .Values.global.environment }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-postgres-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: user-postgres
    tier: data
    app.kubernetes.io/part-of: {{ .Values.global.labels.partOf }}
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
