apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-service-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: user-service
    app.kubernetes.io/part-of: {{ .Values.global.labels.partOf }}
    environment: {{ .Values.global.environment }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedSecrets }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: user-service-secret
      namespace: {{ .Values.global.namespace }}
    type: Opaque
