apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend-service
    app.kubernetes.io/part-of: {{ .Values.global.labels.partOf }}
    environment: {{ .Values.global.environment }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
