apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: product-service-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: product-service
    app.kubernetes.io/part-of: {{ .Values.global.labels.partOf }}
    environment: {{ .Values.global.environment }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedSecrets }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: product-service-secret
      namespace: {{ .Values.global.namespace }}
    type: Opaque
