apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: order-service
    app.kubernetes.io/part-of: {{ .Values.global.labels.partOf }}
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
